server:
  port: 8052
jmx:
  port: 2052

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8087/eureka/
  instance:
    preferIpAddress: true

spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://localhost:50000/DBAUTO
    username: db2admin
    password: admin123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.default_schema: DB2ADMIN

logging:
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss} %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    com.netflix.discovery: "OFF"
    com.gnp.autos.configurador: INFO
