server:
  port: 8055
jmx:
  port: 2052

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka
  instance:
    preferIpAddress: true

spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://localhost:50000/gnpcat
    username: felipe
    password: alsk
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.default_schema: DB2ADMIN
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      javax:
        persistence.sharedCache.mode: ENABLE_SELECTIVE

logging:
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss} %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    com.netflix.discovery: "OFF"
    com.gnp.autos.configurador: INFO

---
spring:
  profiles: developfelipe
  datasource:
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      url: jdbc:db2://localhost:50000/gnpcat
      username: felipe  
      password: alsk  
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.DB2Dialect
      hibernate.default_schema: DB2ADMIN
